# Generated by Django 4.2.3 on 2023-10-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="product",
            field=models.ManyToManyField(
                default="", related_name="product_review", to="product.product"
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="reviews",
        ),
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
