# Generated by Django 4.2.3 on 2023-10-31 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_reviews_product_remove_product_reviews_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="reviews",
        ),
    ]
