# Generated by Django 4.2.3 on 2023-10-31 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_remove_product_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category",
                to="product.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="imgUrl",
            field=models.ImageField(null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="productName",
            field=models.CharField(default="", max_length=255),
        ),
    ]
