# Generated by Django 4.2.3 on 2023-10-31 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_alter_product_category_alter_product_imgurl_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="product",
        ),
        migrations.AddField(
            model_name="reviews",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_review",
                to="product.product",
            ),
        ),
    ]
