# Generated by Django 4.2.3 on 2023-10-31 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_remove_reviews_product_reviews_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_review",
                to="product.product",
            ),
        ),
    ]
