# Generated by Django 4.2.3 on 2023-11-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_alter_reviews_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="userName",
            field=models.CharField(default="", max_length=100),
        ),
    ]
