# Generated by Django 4.2.3 on 2023-11-01 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_alter_reviews_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="user",
        ),
    ]
