# Generated by Django 4.2.3 on 2023-11-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_remove_reviews_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="item_id",
            field=models.IntegerField(default=0),
        ),
    ]
