# Generated by Django 4.1.7 on 2024-12-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_initialprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgUrl',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shortDisc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
