# Generated by Django 5.0.1 on 2025-06-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_imgurl_alter_product_shortdisc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgUrl',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
