# Generated by Django 4.2.3 on 2023-10-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("rating", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productName", models.CharField(max_length=255)),
                ("imgUrl", models.ImageField(upload_to="media/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shortDisc", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField()),
                ("avgRating", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reviews",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.reviews"
                    ),
                ),
            ],
        ),
    ]
